/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAdminRouteImport } from './routes/api/admin'
import { Route as ApiCompaniesRouteImport } from './routes/api/companies'
import { Route as ApiDrinksRouteImport } from './routes/api/drinks'
import { Route as ApiGuestRouteImport } from './routes/api/guest'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiPushRouteImport } from './routes/api/push'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompaniesRoute = ApiCompaniesRouteImport.update({
  id: '/api/companies',
  path: '/api/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrinksRoute = ApiDrinksRouteImport.update({
  id: '/api/drinks',
  path: '/api/drinks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuestRoute = ApiGuestRouteImport.update({
  id: '/api/guest',
  path: '/api/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushRoute = ApiPushRouteImport.update({
  id: '/api/push',
  path: '/api/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/companies': typeof ApiCompaniesRoute
  '/api/drinks': typeof ApiDrinksRoute
  '/api/guest': typeof ApiGuestRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/push': typeof ApiPushRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/companies': typeof ApiCompaniesRoute
  '/api/drinks': typeof ApiDrinksRoute
  '/api/guest': typeof ApiGuestRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/push': typeof ApiPushRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/companies': typeof ApiCompaniesRoute
  '/api/drinks': typeof ApiDrinksRoute
  '/api/guest': typeof ApiGuestRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/push': typeof ApiPushRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/admin'
    | '/api/companies'
    | '/api/drinks'
    | '/api/guest'
    | '/api/profile'
    | '/api/push'
    | '/api/stats'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/admin'
    | '/api/companies'
    | '/api/drinks'
    | '/api/guest'
    | '/api/profile'
    | '/api/push'
    | '/api/stats'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/api/admin'
    | '/api/companies'
    | '/api/drinks'
    | '/api/guest'
    | '/api/profile'
    | '/api/push'
    | '/api/stats'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiCompaniesRoute: typeof ApiCompaniesRoute
  ApiDrinksRoute: typeof ApiDrinksRoute
  ApiGuestRoute: typeof ApiGuestRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiPushRoute: typeof ApiPushRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/companies': {
      id: '/api/companies'
      path: '/api/companies'
      fullPath: '/api/companies'
      preLoaderRoute: typeof ApiCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drinks': {
      id: '/api/drinks'
      path: '/api/drinks'
      fullPath: '/api/drinks'
      preLoaderRoute: typeof ApiDrinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guest': {
      id: '/api/guest'
      path: '/api/guest'
      fullPath: '/api/guest'
      preLoaderRoute: typeof ApiGuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push': {
      id: '/api/push'
      path: '/api/push'
      fullPath: '/api/push'
      preLoaderRoute: typeof ApiPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiCompaniesRoute: ApiCompaniesRoute,
  ApiDrinksRoute: ApiDrinksRoute,
  ApiGuestRoute: ApiGuestRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiPushRoute: ApiPushRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
